### ISSUE TITLE
Goloop make fails at RocksDB

### ISSUE THREAD

**Issue by meshachj** [icon-project/goloop#106]
I have been following the build guide found here: https://github.com/icon-project/goloop/blob/master/doc/build.md

The following are my specs and current versions
<img width="583" alt="Screen Shot 2022-04-26 at 9 49 07 PM" src="https://user-images.githubusercontent.com/10481638/165429771-a7c70805-9b3b-4a1d-a7ec-f5d8121cded3.png">
- `go 1.18.1`
- `python 3.10.2`
- `rocksdb 7.0.3`

After installing the required packages and pip libraries, I get the following output when running make in the goloop directory.
```
~/goloop (master) » make                                                        
[#] go build ./cmd/gochain
go build -tags "rocksdb" -ldflags "-X 'main.version=v1.2.4-10-gcd14224f' -X 'main.build=darwin/arm64 tags(rocksdb)-2022-04-26-21:39:13'" -o /Users/shack/goloop/bin/gochain ./cmd/gochain
# github.com/icon-project/goloop/common/db
common/db/rocks_db.go:34:11: fatal error: 'rocksdb/c.h' file not found
 #include "rocksdb/c.h"
          ^~~~~~~~~~~~~
1 error generated.
make: *** [gochain] Error 2
```

**Comment by yakkle** [comment]
@meshachj 
https://icondev.io/icon-node/goloop/get-started/build#mac-m1-apple-silicon
