### ISSUE TITLE
Checksum Mismatch

### ISSUE THREAD

**Issue by salvation-al** [icon-project/goloop#109]
When I try and build my Golang application referencing any goloop files, this happens...

go: downloading github.com/icon-project/goloop v1.2.6
verifying github.com/icon-project/goloop@v1.2.6: checksum mismatch
        downloaded: h1:aqTdUbAeHMvcUo3+QFsSynS/MNvsD7yCDkjrNuw1Hrg=
        sum.golang.org: h1:9FFSFWTAk3c6sAmR3/vdO3fgh3Wwq0AUDoEFo2A4xf0=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

**Comment by mksong-icon** [comment]
Accidently, we have uploaded invalid tags on merging some branches. They are removed for now, but if they are pulled by someone, then you can see the security problems. I don't know how to resolve the problems, but you might see these problems in future versions also.

Unfortunately, according to their FAQ (https://sum.golang.org/), they can't be replaced or removed.
Invalid tags what we know are the following: v1.2.6 ~ v1.2.12. Sorry for your inconvenience.

Until we release a new higher version than the invalid tags, it may continue.

**Comment by sink772** [comment]
This issue is now resolved as goloop v1.2.13 was released.
