### ISSUE TITLE
Missing block notifications in ICON btp_extension's websocket endpoint: /block

### ISSUE THREAD

**Issue by bbist** [icon-project/goloop#113]
We made the following observation (in screenshot) when using [wss://ctz.solidwallet.io/api/v3/icon_dex/block](url) websocket endpoint.

Some of the successive block notifications were not consecutive. This lead to missing blocks in the chain and the verification failed. We're using the btp_extension endpoints (/block) in relay.

Missing block notifications that have no subscribed events can be handled in the relay. We were concerned about whether the endpoint also misses block notifications for the blocks that include subscribed events. Looks like it does.

Following screenshot shows the missing block notifications from ICON. Please look at the heights.

![image](https://user-images.githubusercontent.com/76272791/174015393-abbfe748-302e-4678-a55f-cef122300442.png)

Following screenshot shows the actual values when it doesn't miss anything. We reconnected the websocket to get the second one. So, one solution would be to simply reestablish the websocket connection and try again. I guess this is the simplest solution for now. But I hope we can look into it in goloop and fix the root cause.

![image](https://user-images.githubusercontent.com/76272791/174015448-eab86827-efb9-41bc-9348-d0acc4b13cda.png)

NOTE: We cannot reproduce this with certainty, and have only observed this infrequently.

**Comment by mksong-icon** [comment]
@bbist It's impossible to send WebSocket messages skipping some blocks according to the codes.

While it makes a message to send, it uses `h` variable in the loop.
https://github.com/icon-project/goloop/blob/bb933e37d57d26c61a941816ab9b18196cd00280/server/wsblock.go#L76
And it's increased at the following line
https://github.com/icon-project/goloop/blob/bb933e37d57d26c61a941816ab9b18196cd00280/server/wsblock.go#L123

There are two breaks before sending messages, and all of them result in disconnection.
So, it prints blocks with proper heights until it's disconnected.

I think that it may come from other parts not by GOLOOP.

Please check yours more closely.
