### ISSUE TITLE
tcp: no such host

### ISSUE THREAD

**Issue by BananaSquares** [icon-project/goloop#117]
Followed the instructions in the tutorial and the server is giving this.
![image](https://user-images.githubusercontent.com/60858870/182462909-89303113-f84f-4472-9f44-07dafe83acca.png)

**Comment by sink772** [comment]
What tutorial did you follow? and what's your problem?

**Comment by BananaSquares** [comment]
> What tutorial did you follow? and what's your problem?

The tutorial in the repository, tutorial.md. I was assuming that message was a problem but perhaps that’s not the case

**Comment by sink772** [comment]
As the error message indicates, you need to set proper host name for the seed server.
`server0` in the tutorial is just a symbolic name, it should not be used as it is.
