### ISSUE TITLE
UnmodifiableArrayMap values returns keys

### ISSUE THREAD

**Issue by AntonAndell** [icon-project/goloop#123]
At collect method the offset parameter is ignored:
https://github.com/icon-project/goloop/blob/d4569e3c0e5f38489a8400b3e7dc7a7c01da2172/javaee/rt/src/java/pi/UnmodifiableArrayMap.java#L58-L67

This makes both values and keys return keys:
https://github.com/icon-project/goloop/blob/d4569e3c0e5f38489a8400b3e7dc7a7c01da2172/javaee/rt/src/java/pi/UnmodifiableArrayMap.java#L68-L71

https://github.com/icon-project/goloop/blob/d4569e3c0e5f38489a8400b3e7dc7a7c01da2172/javaee/rt/src/java/pi/UnmodifiableArrayMap.java#L73-L76

**Comment by sink772** [comment]
Revision 20 proposal has been applied to mainnet.
https://tracker.icon.community/proposal/0x1f53e4dbcf1fafea1a7f46ee427142c6a9035b359fa2e9f47804c9066d999b60
So close as completed.
