### ISSUE TITLE
We had this error on Mainnet

### ISSUE THREAD

**Issue by UbikCapital** [icon-project/goloop#133]
|20221211-01:58:16.911052|54d6|1|BM|manager.go:826 ImportBlock(626c1765771dba0f0183911e447443427c55d3745fd63f017e1ed9c66a2f9200)
P|20221211-01:58:16.911085|54d6|1|CS|consensus.go:935 commitAndEnterNewHeight: InvalidPreviousID(cbbdcab71a483b4ca75ba1c56e219d6ce7702ac95af7135c49e17dd43397c1b6)
[github.com/icon-project/goloop/block.(*manager)._import](http://github.com/icon-project/goloop/block.(*manager)._import)
        /work/block/manager.go:310
[github.com/icon-project/goloop/block.(*manager).ImportBlock](http://github.com/icon-project/goloop/block.(*manager).ImportBlock)
        /work/block/manager.go:828
[github.com/icon-project/goloop/consensus.(*consensus).commitAndEnterNewHeight](http://github.com/icon-project/goloop/consensus.(*consensus).commitAndEnterNewHeight)
        /work/consensus/consensus.go:909
[github.com/icon-project/goloop/consensus.(*consensus).enterCommit](http://github.com/icon-project/goloop/consensus.(*consensus).enterCommit)
        /work/consensus/consensus.go:973
[github.com/icon-project/goloop/consensus.(*consensus).processBlock](http://github.com/icon-project/goloop/consensus.(*consensus).processBlock)
        /work/consensus/consensus.go:2074
[github.com/icon-project/goloop/consensus.(*consensus).ReceiveBlock](http://github.com/icon-project/goloop/consensus.(*consensus).ReceiveBlock)
        /work/consensus/consensus.go:2025
[github.com/icon-project/goloop/consensus.(*syncer).OnBlock](http://github.com/icon-project/goloop/consensus.(*syncer).OnBlock)
        /work/consensus/syncer.go:509
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1571
panic: (*logrus.Entry) 0xc006be3d50

goroutine 7384577 [running]:
[github.com/sirupsen/logrus.Entry.log({0xc0000e6070](http://github.com/sirupsen/logrus.Entry.log(%7B0xc0000e6070), 0xc00071cf90, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x0, ...}, ...)
        /go/pkg/mod/[github.com/sirupsen/logrus@v1.6.0/entry.go:259](http://github.com/sirupsen/logrus@v1.6.0/entry.go:259) +0x2de
[github.com/sirupsen/logrus.(*Entry).Log(0xc000372b60](http://github.com/sirupsen/logrus.(*Entry).Log(0xc000372b60), 0x0, {0xc02a93dc70?, 0x1?, 0x1?})
        /go/pkg/mod/[github.com/sirupsen/logrus@v1.6.0/entry.go:287](http://github.com/sirupsen/logrus@v1.6.0/entry.go:287) +0xa8
[github.com/sirupsen/logrus.(*Entry).Logf(0xc000372b60](http://github.com/sirupsen/logrus.(*Entry).Logf(0xc000372b60), 0x0, {0x149244a?, 0x86e0c7?}, {0xc0510b8780?, 0x12db7e0?, 0xc02a93dc01?})
        /go/pkg/mod/[github.com/sirupsen/logrus@v1.6.0/entry.go:333](http://github.com/sirupsen/logrus@v1.6.0/entry.go:333) +0x85
[github.com/sirupsen/logrus.(*Entry).Panicf(0xc0001aea90](http://github.com/sirupsen/logrus.(*Entry).Panicf(0xc0001aea90)?, {0x149244a?, 0xc041bc3e60?}, {0xc0510b8780?, 0x0?, 0xc00023cb10?})
        /go/pkg/mod/[github.com/sirupsen/logrus@v1.6.0/entry.go:371](http://github.com/sirupsen/logrus@v1.6.0/entry.go:371) +0x34
[github.com/icon-project/goloop/consensus.(*consensus).commitAndEnterNewHeight(0xc000192840)](http://github.com/icon-project/goloop/consensus.(*consensus).commitAndEnterNewHeight(0xc000192840))
        /work/consensus/consensus.go:935 +0x1c6
[github.com/icon-project/goloop/consensus.(*consensus).enterCommit(0xc000192840](http://github.com/icon-project/goloop/consensus.(*consensus).enterCommit(0xc000192840), 0x15fe728?, 0xc0015527c0, 0x0)
        /work/consensus/consensus.go:973 +0x3c6
[github.com/icon-project/goloop/consensus.(*consensus).processBlock(0xc000192840](http://github.com/icon-project/goloop/consensus.(*consensus).processBlock(0xc000192840), {0x15fb6d8, 0xc0419fd810})
        /work/consensus/consensus.go:2074 +0x69e
[github.com/icon-project/goloop/consensus.(*consensus).ReceiveBlock(0xc000192840](http://github.com/icon-project/goloop/consensus.(*consensus).ReceiveBlock(0xc000192840), {0x15fb6d8, 0xc0419fd810})
        /work/consensus/consensus.go:2025 +0x205
[github.com/icon-project/goloop/consensus.(*syncer).OnBlock(0xc00023ca80](http://github.com/icon-project/goloop/consensus.(*syncer).OnBlock(0xc00023ca80), {0x15fb6d8, 0xc0419fd810})
        /work/consensus/syncer.go:509 +0x150
created by [github.com/icon-project/goloop/consensus/fastsync.(*client).notifyBlockResult](http://github.com/icon-project/goloop/consensus/fastsync.(*client).notifyBlockResult)
        /work/consensus/fastsync/client.go:354 +0xef

**Comment by mksong-icon** [comment]
Thanks for your report.

To investigate more, we need more information.

1. Version of your node ( can be checked "goloop version" ) or check docker image inspection.
2. More log lines(nearly 1000?) near the error to know the situation

Thanks

**Comment by robcxyz** [comment]
I had a node crash around the same time but have since lost the logs as they have been vacuumed. Next time will grab them.

**Comment by UbikCapital** [comment]
> 

The version is v1.3.1
You can find here the logs: [https://we.tl/t-xnBdaLBGwJ]

**Comment by hijung-icon** [comment]
The log in the link only has messages up to 20221211-00:00:23.800025.
Can you send the next log file?
Thank you in advance.

**Comment by robcxyz** [comment]
Sorry, I forgot the prior days logs were preserved. Here is a link to the logs from a node that crashed at same time https://we.tl/t-H4iF16XzKu

**Comment by hijung-icon** [comment]
FYI, the issue was fixed in the commit
https://github.com/icon-project/goloop/commit/7151326e1f3e71e36542feda1e8a34931d9cf62f
and it is included in [v1.3.3](https://github.com/icon-project/goloop/releases/tag/v1.3.3).
The version is being tested in test net. It will be applied to the main net soon after the test in the test net.
Thank you.
