### ISSUE TITLE
Dependeny warning yaml

### ISSUE THREAD

**Issue by paulrouge** [icon-project/goloop#135]
I get a dependency warning when importing gopkg.in/yaml.v2 v2.2.1 and v2.2.2 (lines 220 - 222) via the go.sum file.

It throws this warning: 

“The Kubernetes API Server component in versions 1.1-1.14, and versions prior to 1.15.10, 1.16.7 and 1.17.3 allows an authorized user who sends malicious YAML payloads to cause the kube-apiserver to consume excessive CPU cycles while parsing YAML.”

I fixed it by setting the versions to v2.2.8. Should be something to look at, perhaps.

**Comment by mksong-icon** [comment]
fixed in https://github.com/icon-project/goloop/commit/3e470dcb99f6b468e4843d52043d78a1b334b6f8
