### ISSUE TITLE
Determining number of missed blocks / terms from `getPRepStats`

### ISSUE THREAD

**Issue by robcxyz** [icon-project/goloop#147]
I am trying to gather some data for the tracker and discord / telegram bots that will show how many missed blocks / terms a prep has endured so that we can warn people of when they will be slashed when that takes effect. I have a question about how to collect this data as I have been looking at `getPRepStats` contract method on cx000..0 which returns:

```
{
    'fail': 2636,
    'failCont': 2,
    'grade': 2,
    'lastHeight': 63357888,
    'lastState': 0,
    'penalties': 3,
    'realFail': 2636,
    'realFailCont': 2,
    'realTotal': 772069,
    'status': 0,
    'total': 772069
}
```
For preps that look like they are in trouble where `realFailCont` is non-zero. Issue is that I only see this for 3 preps currently. 

Eye on ICON
ICON Sweden
MouseBelt | Multi.io

I would expect to see this for more preps as there are many who have turned their node off and still have high stake / power.  Am I missing something or is there something else I should be looking at. Previous discussions about `realFailCont` said:

```
    realFailCont reset when a node votes on a block only.
    1. At Term(n) : Node(A) missed last 2 blocks
    2. At Term(n+1): Node(A) was not elected as a Validator
    3. At Term(n+2): Node(A) missed first 3 blocks til Block(N).
    4. At Block(N): Node(A) got realFailCont: "0x5"
    5. At Block(N+1): If Node(A) votes, realFailCont will be reset
```
So from this, I would expect far more preps to have non-zero values. 

To be clear, we just want to be able to warn people when their node is going to be slashed and planning on using this data within the governance page in the tracker and in various bots to alert people. 

Thank you for your time.

**Comment by eunsoo-icon** [comment]
There is 2 penalties about block validation.
- Validation Failure Penalty
definition: Failed to validate 660 blocks in a row.
penalty: Exclude the P-Rep from the validator set of the Term temporarily. P-Rep can't get P-Rep rewards for remaining blocks of the Term.
data: `getPRepStats.realFailCont` == 660

-  Accumulated Validation Failure Penalty
definition: Get penalized 5 times or more with `Validation Failure Penalty` in 30 opportunities.
penalty: Slashing. Slashing rate is determined by Network Proposal. Current slashing rate is 0.
data: `getPRepStats.penalties` >= 5

Use case
```
{
    'fail': 2636,
    'failCont': 600,
    'grade': 2,
    'lastHeight': 63357888,
    'lastState': 0,
    'penalties': 4,
    'realFail': 2636,
    'realFailCont': 600,
    'realTotal': 772069,
    'status': 0,
    'total': 772069
}
```
1. P-Rep fails to validate additional 60 blocks
=> P-Rep get `Validation Failure Penalty` and `Accumulated Validation Failure Penalty`.
2. At the next Term, P-Rep fails to validate 660 blocks again.
=> P-Rep again get `Validation Failure Penalty` and `Accumulated Validation Failure Penalty` again.

**Comment by robcxyz** [comment]
Hi @eunsoo-icon - Thank you for the detailed response. 

I went ahead and exposed the stats over the endpoint:

Preps with `realFailCont` - https://tracker.icon.community/api/v1/governance/preps?failure_count=true
Preps with `penalties` - https://tracker.icon.community/api/v1/governance/preps?penalties=true
[API Docs](https://tracker.icon.community/api/v1/governance/docs#/default/get_preps_api_v1_governance_preps_get)

What I see is that there are 30 nodes with penalties which makes sense. Although there are only about 50 active prep nodes on the network now, the penalties only are given to those with any power that could be put in the main rotation so it makes sense that there aren't more nodes getting penalties. 

What I am confused about though is the number of nodes with `realFailCont` as the max value I have seen is 2 and I have seen over 5 nodes have that value. I think this is not incrementing up to 660 as you mentioned. It would be helpful for us being able to warn nodes that they are missing blocks if this number rose to 660 which we can set alarms over. It is ok for the time being as we'll just treat any node that has `realFailCont` ("failure_cont" in the response) as being in a failure condition and give a warning / change the color of their icon in the governance page. 

Is this expected to not have `realFailCont` go higher than 2?

Just wanted to raise this, share the endpoints, and the findings.

**Comment by eunsoo-icon** [comment]
If P-Rep get `Validation Failure Penalty`, `realFailCont` is reset to 0 and P-Rep is excluded from validator set. So it's hard to see bigger `realFailCont`.

You can call `icx_call` method with `height` parameter.

Here is an example of `getPRepStats` where `realFailCont` > 0x2. Two P-Reps get penalty at Block Height `0x3a7d499`.
```
{
    "jsonrpc": "2.0",
    "method": "icx_call",
    "id": 1234,
    "params": {
        "to": "cx0000000000000000000000000000000000000000",
        "dataType": "call",
        "height": "0x3a7d498",
        "data": {
            "method": "getPRepStats",
            "params": {}            
        }
    }
}
```

**Comment by robcxyz** [comment]
@eunsoo-icon - Thanks, that is very helpful. Going to be polling that frequently. Appreciate your time.
