### ISSUE TITLE
Ask for confirmation when creating a wallet with same name using goloop cli

### ISSUE THREAD

**Issue by izyak** [icon-project/goloop#172]
If I try to create a keystore using the goloop cli, 
```sh
goloop ks gen -o master_key.json -p mystrongpassword
```

A file master_key.json is generated. 

--- 

However, if I run the same command again, the keystore is replaced with a new one, and I lose the previous keystore. It would be better to ask for confirmation before allowing to create keystore with the same name.

**Comment by mksong76** [comment]
goloop is also used for a shell script, so the interactive response is not a required feature.
