### ISSUE TITLE
Deprecation of node_address and clarity on public key 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/goloop#177]
It is my understanding that setting the node address (the address that used to be able to be set via `setPrep` which can be used on the node in place of a prep address) has been deprecated and I just wanted to get a little clarity with how it interacts with the `registerPRepNodePublicKey` and `setPRepNodePublicKey` methods. If you could please correct me if I am wrong, the node address now is still able to be registered but instead of using `setPrep`, one creates a public key from it using:

```shell
goloop ks pubkey -k keystore -p <password> 
```

You would then move the keystore on to a node and then run the `setPRepNodePublicKey` method with the prep address as the signer to change the registration to the new keystore that created the public key. 

Is this all correct? 

As a side note, the `setPrep` method still has nodeAddress field in the ABI and when you use it, you get the log:

```
FRAME[2] INVOKE done status=InvalidParameter msg=E0006:Can't modify node address by setPRep method of chain SCORE steps=0
```

I can raise a PR to remove that field from the setPrep if needed as it seems like it should not be there. 

Thank you for your time.

**Comment by mksong76** [comment]
After enabling BTP network(Rev21), it should use `setPRepNodePublicKey` to change the node address of the PRep instead of using `setPRep`.

**Comment by robcxyz** [comment]
Ok thanks.
