### ISSUE TITLE
Pushing artifacts and goloop / gochain images to dockerhub on release of new goloop 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/goloop#179]
I am trying to setup a one-click local gochain with tracker and I am wondering if I can contribute a github workflow to build and push these artifacts / images to github / docker hub on each release? This would take a step out of the process where I would need to instruct the user to clone this repo and build the images themselves. Also would be generally more convenient for users to be able to use pre-compiled binaries / built images instead of having to go to source each time. 

I did a quick PR that has the docker build / push but would need to have secrets setup for the dockerhub login and repos for the images set up by you for this to work. If this is of interest, I can also contribute the artifacts as well.

**Comment by sink772** [comment]
We are already managing the following docker hub for `goloop-icon` image.

https://hub.docker.com/r/iconloop/goloop-icon/tags

**Comment by robcxyz** [comment]
Is this the same as the output of `make gochain-image`? I thought that image was from icon2-docker which is slightly different. This slightly relates to https://github.com/icon-project/gochain-local/pull/8 where the instructions say to make this image. Just thought it would be nice to have all these other less used images pushed to docker hub. Also a goloop binary in release artifacts.

**Comment by sink772** [comment]
That is the same as the output of `make goloop-icon-image`, not `make gochain-image`.

I think you are very misunderstood about how to build the goloop image for ICON.  You should use the `goloop-icon-image` target for ICON platform.  (for gochain build, you should use `gochain-icon-image` target). 

[icon2-node](https://hub.docker.com/r/iconloop/icon2-node) is a special docker image for ICON PReps, which is based on the above goloop-icon-image and some additional features (like automatic mainnet/testnet DB restoration) are included.

So for the general local testnet environment, `goloop-icon` (or `gochain-icon`) would suffice.

If you want to see an example of how to use the above `iconloop/goloop-icon` image, you can refer to the following e2edemo config in the BTP2 repo.
https://github.com/icon-project/btp2/blob/main/e2edemo/docker/docker-compose.yml

**Comment by robcxyz** [comment]
Hi - Forgot to close this but as I mentioned in adjacent issues - the make command I was using was the culprit as you pointed out and the image that I needed was already on docker hub as seen in the btp repo you linked. I used it to make this https://github.com/sudoblockio/gochain-local-community 

Thanks for help though.
