### ISSUE TITLE
Event subscription automatically closes after > 45 secs.

### ISSUE THREAD

**Issue by debendraoli** [icon-project/goloop#202]
The `/event` websocket connection closes after certain time interval.

I tried enabling `progressInterval` to least duration, thats seems slow down the disconnection but not prevent it.

In a meantime I have to reconnect to handle the disconnected subscription, it appears there's no other way around.

**Comment by sink772** [comment]
Where did you try to connect for the event websocket?

`goloop` engine itself does not have such a timeout limitation, but if you were using the public citizen node (i.e., `ctz.solidwallet.io`), there might be a timeout setting by nginx reverse proxy.

Thus, general and preferred recommendation is, if you are using the API endpoint server (i.e., citizen node) seriously for you own service, you need to run your own API server where there is no such a timeout.

**Comment by debendraoli** [comment]
fixed after setting `progressInterval` to `15` second.

**Comment by debendraoli** [comment]
`25s` also works but not more than that.

**Comment by sink772** [comment]
@debendraoli, as I mentioned before, your problem has nothing to do with `goloop` itself, but with the public citizen's ngnix setup.

I will close this issue, since there is nothing more to discuss from `goloop` perspective

Again, you should run your own API endpoint server for your service.
