### ISSUE TITLE
Error when building goloop-0.9.4

### ISSUE THREAD

**Issue by Spl3en** [icon-project/goloop#27]
Hello,

I got this error when following the build instructions on a Linux & Mac environment : 

```
$ wget https://github.com/icon-project/goloop/archive/v0.9.4.zip && unzip v0.9.4.zip && cd goloop-0.9.4
$ python3 -m venv ./venv
$ source ./venv/bin/activate
$ pip3 install -r pyee/requirements.txt
$ make
```

It outputs the following error

```
go build ./cmd/goloopgo build -tags "" -ldflags "-X 'main.version=v0.9.4' -X 'main.build=linux/amd64 tags()-2021-02-02-16:41:28'" -o ./bin/goloop ./cmd/goloop
# github.com/icon-project/goloop/icon/iiss
icon/iiss/base.go:212:2: cannot use tx (type *baseV3) as type transaction.Transaction in return argument:
    *baseV3 does not implement transaction.Transaction (missing IsSkippable method)
icon/iiss/base.go:233:2: cannot use tx (type *baseV3) as type transaction.Transaction in return argument:
    *baseV3 does not implement transaction.Transaction (missing IsSkippable method)
```

Is there's something missing in the build instructions or am I missing something ?

Thanks!

**Comment by Spl3en** [comment]
I managed to compile goloop v0.9.5 on the "base" branch.
Could you update the .zip in the Release?

```
$ ./bin/goloop version
goloop version v0.9.5 linux/amd64 tags()-2021-02-02-17:35:05
```

**Comment by mksong-icon** [comment]
The .zip file is managed by github.com. It's automatically generated by the tagged source.
We already know that v0.9.4 has a build problem.  It would be removed or marked as "broken" to let you know that it's not usable.

**Comment by sink772** [comment]
Hi @Spl3en 

You can find the zip file of v0.9.5 at https://github.com/icon-project/goloop/archive/v0.9.5.zip
It seems github only regards tags with the default branch as latest, but you can browse all the tags at Release section.
