### ISSUE TITLE
Failure in interscore  calls

### ISSUE THREAD

**Issue by Deceivious** [icon-project/goloop#64]
#### Issue Description:
While calling an interface method to another score with paramters, the transactions are failing with the status "Fail - InvalidParameter". This issue was noted on Sejong test environment.

#### Successful Transaction in Yeouido:
https://bicon.tracker.solidwallet.io/transaction/0x77484a6d52fe348fea65a7e6679f35a299b3b947a7ede671883a06338325ca69#events

#### Relevant Debugger traceback snippet:
```
{
      "Level": 1,
      "Msg": "internal_call.py:59 [InternalCall] \u003e\u003e\u003e from=cxf49965a5aa819392af71721de15729b4b3235c21 to=cx7bb72aa63ecf1417344f815bfb90cc86202f2412 amount=0 func_name=create_character_record"
    },
    {
      "Level": 1,
      "Msg": "internal_call.py:60 [InternalCall]     new_limit=1732400, params=()"
    },
    {
      "Level": 2,
      "Msg": "FRAME[2] CALL start from=cxf49965a5aa819392af71721de15729b4b3235c21 to=cx7bb72aa63ecf1417344f815bfb90cc86202f2412 value=0 steplimit=1732400 dataType=call data={\"method\":\"create_character_record\",\"params\":[]}"
    },
    {
      "Level": 2,
      "Msg": "FRAME[3] START parent=FRAME[2]"
    },
    {
      "Level": 2,
      "Msg": "FRAME[3] INVOKE start score=cx7bb72aa63ecf1417344f815bfb90cc86202f2412 method=create_character_record"
    },
    {
      "Level": 2,
      "Msg": "FRAME[3] STEP apply type=contractCall count=1 cost=25000 total=25000"
    },
    {
      "Level": 2,
      "Msg": "FRAME[3] INVOKE done status=InvalidParameter msg=E0006:NotEnoughParameters(given=0,required=2) steps=25000"
    },
```

#### Code Snippet:
```
 @external
    def set_nft_characters(self, nft_info: str):
        require(self.msg.sender in [self.admin_address.get(), self.owner], "Only admin can set NFT characters.")
        nft_info = json_loads(nft_info)

        for nft_id, nft_value in nft_info.items():
            nft_id = int(nft_id)
            is_gangster, character_class, token_uri = nft_value
            require(character_class in ADDITIONAL_SKILL_MAPPING[int(is_gangster)].keys(),
                    f"Invalid class '{character_class}'.")

            _character_db = self.character_db[self._generate_byte_code(nft_id)]
            require(self.character_db[self._generate_byte_code(nft_id)].token_uri.get() == "",
                    "Information for the NFT has already been set.")
            _character_db.is_gangster.set(is_gangster)
            _character_db.character_class.set(character_class)
            _character_db.token_uri.set(token_uri)

            self.NFTCharactersSet(nft_id, is_gangster, character_class, token_uri)

            # REGISTER CHARACTER IN SKILL DATABASE
            creation_date = _character_db.creation_date.get()
            skill_interface = self.create_interface_score(
                addr_to=self.skill_score_address.get(),
                interface_cls=SkillInterface
            )
            skill_interface.create_character_record(nft_id=nft_id, creation_date=creation_date)
```

**Comment by Deceivious** [comment]
Hi Team, 

We made the following changes on the code and the tx is now working.

Before: 
`skill_interface.create_character_record(nft_id=nft_id, creation_date=creation_date)`
After:
`skill_interface.create_character_record(nft_id, creation_date)`

Failed Tx in code with argument name specified:
https://sejong.tracker.solidwallet.io/transaction/0xaa0eb6128fe518616d1ec312f462dee151dfe90c4cbc959f457a4e85b0cfaee5

Successful Tx in code with no argumennt name specified :https://sejong.tracker.solidwallet.io/transaction/0xb8338f137dc4146578fedf2577ec90790dc011c63358b01f6b05fd1c70de51c8

It seems that passing the arguement name is calling an issue.

**Comment by mksong-icon** [comment]
It's already fixed with the following commits
* https://github.com/icon-project/goloop/commit/374097684bedbc0f4f160a1778252ff2075099f8
* https://github.com/icon-project/goloop/commit/1384dd0250f803a131196f3c9dbee5fa25a57d3e
But you can continue with the patch.

**Comment by Deceivious** [comment]
Hi @mksong-icon,


We are using the named argument method calls is multiple areas and patching all of the method calls would take lots of development. Since, the hard stop date on Python deployment on icon 1 is set on 17th September, we should be able to test all the scores in Sejong by end of this week.

When is the plan to deploy this into Sejong testnet?

**Comment by sink772** [comment]
Closed as the recent Sejong testnet reflects the change.
