### ISSUE TITLE
 How to pass array as parameter *on deploy* using goloop CLI ?

### ISSUE THREAD

**Issue by ICONationDevTeam** [icon-project/goloop#67]
Hello,

I'd like to know if that's possible to pass an array as a parameter of `goloop rpc sendtx deploy`.
This issue is slightly related to https://github.com/icon-project/goloop/issues/66 .

Right now the documentation only mentions a `--param` flag, but doesn't accept a `--raw` flag like `goloop rpc call`.

Is there an existing format for passing an array as a parameter using `--param` ?

---

Repro:

```java
package com.iconloop.score.example;

import java.math.BigInteger;

import score.Context;
import score.ArrayDB;
import score.annotation.External;

public class HelloWorld {

    private final ArrayDB<BigInteger> array = Context.newArrayDB("array", BigInteger.class);

    public HelloWorld(BigInteger[] _array) {
        for (var item : _array) {
            this.array.add(item);
        }
    }

    @External(readonly = true)
    public BigInteger get_item (int index) {
        return this.array.get(index);
    }
}
```

Goloop CLIP command : 
```bash
goloop rpc sendtx deploy helloworld-optimized.jar \
    --content_type application/java \
    --key_store ${key_store} \
    --key_password=${key_password} \
    --nid ${nid} \
    --step_limit ${step_limit} \
    --uri ${uri} \
    --param _array=???
```

**Comment by sink772** [comment]
Yeah... currently the CLI interface doesn't support complex types like array as an input parameter.

You could use `raw` or `raw2` sub-command in `sendtx` to send transaction with a json file, but if you want to use this command in deployment scenario, you need to convert the jar file into large hexastring and save it into the json file, this is somewhat cumbersome.

The CLI interface is for quick query or invoking transactions on-the-fly, not for working with testing framework or official deployment. Thus I'd like to recommend to use ICON SDK either [Java](https://github.com/icon-project/icon-sdk-java) or [Python](https://github.com/icon-project/icon-sdk-python) for your testing or official deployment.  Please refer to [deploy script](https://github.com/sink772/multi-token-standard/blob/main/scripts/deploy_contract.py) in [Multi-Token Standard](https://github.com/sink772/multi-token-standard) repository.

**Comment by ICONationDevTeam** [comment]
Thanks ! I'll move on SDKs then.
