### ISSUE TITLE
Allow BigInteger up to 33 bytes in order to store UINT256_MAX ?

### ISSUE THREAD

**Issue by ICONationDevTeam** [icon-project/goloop#69]
In the current goloop version, we can't deploy the following statement without raising an exception:

```java
BigInteger MAX_UINT256 = new BigInteger("ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", 16);
```

```log
Caused by: java.lang.ArithmeticException
       at s.java.math.BigInteger.isValidLength(BigInteger.java:399)
       at s.java.math.BigInteger.setUnderlying(BigInteger.java:362)
       at s.java.math.BigInteger.<init>(BigInteger.java:28)
       at s.java.math.BigInteger.<init>(BigInteger.java:32)
       at u.x.x.x.HelloWorld.<init>(Unknown Source)
```

Indeed, the underlying BigInteger bytearray is 33 bytes long as it stores the number sign.

https://github.com/icon-project/goloop/blob/bfeb09683738396986311407875eba209ffb1b77/javaee/rt/src/java/s/java/math/BigInteger.java#L396-L402

That makes things complicated for 256 bits unsigned int arithmetic. That's something usual in other smart contract programming languages, so porting becomes problematic with that limitation.

Would it be possible to increase that limit ?

**Comment by hijung-icon** [comment]
I agree to support at least uint256 range.

19cdc39c4e25af2085fb68069f26d991ad80f362 allows java contract to use BigInteger in the closed range [int256 min, uint256 max].

Thank you.
