### ISSUE TITLE
Calling a write method in immutable mode

### ISSUE THREAD

**Issue by ICONationDevTeam** [icon-project/goloop#71]
Hello,

I'm looking for a way to call a write method without modifying the DB state.

Here's my use case : let's say I have the following  `get_result` function: 

```java
@External(readonly = true)
public BigInteger get_result () {
    this._some_very_complex_function(); // this method writes to the SCORE DB and modifies this.result
    return this.result.get(); // returns the value after state change
}
```

`_some_very_complex_function` is an internal method that updates the SCORE DB state, including `this.result` VarDB.

The purpose of calling `get_result` is to be able to read the  `result` value **after a state change**, **without actually modifying it**.

However, as `get_result` is a **readonly method**, calling it will end into a `status=E0009:AccessingWritableFromReadOnly` error.

----

EVM allows calling write methods in readonly without modifying the contract state. 
I know goloop also have a debug estimate step API that do this too. However, I haven't found a way to return the result of the method called, but only the estimated steps.

Is there a way to achieve what I'm looking for ?

-----

Alternatively, I can rewrite `_some_very_complex_function` in order to avoid writing to the SCORE DB and write in temporary local variables instead. However, `_some_very_complex_function` is really big and complex, duplicating it would take a lot of contracts bytes (which is pretty limited), and wouldn't be great for maintainbility.

**Comment by ajaya-man** [comment]
If you don't want the change to be permanent, the hack would be to revert the result after the computation.

**Comment by sink772** [comment]
As you may know, only the following simple rules apply on invoking other contracts.
* readonly -> readonly
* writable -> readonly, writable

There is no other exception here.
It's a non-sense to invoke a writable method from a readonly method.

It seems you already know the solution. You need to refactor your code whatever it is to avoid the situation.

**Comment by ICONationDevTeam** [comment]
@ajaya-man I want the method to be called without signing a transaction. So revert is not what I'm looking for.

@sink772 Actually, I should have explained it in another way.
Let's say `get_result` is now a write method.

```java
@External
public BigInteger get_result () {
    this._some_very_complex_function(); // this method writes to the SCORE DB and modifies this.result
    return this.result.get(); // returns the value after state change
}
```

You said `writable -> readonly, writable`.
Is there a way to call that method in an immutable context so I can retrieve the `get_result` return variable ?

If I try to call that method as a `icx_call` transaction, I got an `E0009:AccessDenied`. I'd want the result of that method.

EVM allows it. It has many usage, AFAIK it's a widely used for arbitrage purposes, so it's not a non sense.

**Comment by sink772** [comment]
As you know, `icx_call` semantic is different from the `eth_call`. That's the design we built, and I think we cannot change its behavior because that may cause some incompatibility issues and make a confusion to the dev community.

From my understanding, it seems you want a slight variant version of `debug_estimateStep` (with returning the execution result **synchronously**).  Anyway we need either to add new JSON-RPC API (so called `icx_invoke`? or `icx_call2`?) or to modify the existing interface to fulfill your request. Either way, it's not an easy decision.  Even in the internal dev discussion, we could not conclude anything.

**Comment by ICONationDevTeam** [comment]
Hey @sink772 , sorry for the late reply, I didn't have the notification you replied.

Firstly, thanks for the detailed answer. I understand the feature does not exist. You're correct about it being a modified version of `debug_estimateStep` that actually return the result of the method called instead of the steps consumed.

I understand it's not a feature that will be used by basic SCORE programmers, so I can understand if you're hesitating implementing it. However I believe it's an optimization that'd be very useful for advanced SCORE programmers, similarly to CREATE2 opcode on ETH.
I'm considering the alternatives, but I don't think a SCORE contract should reimplement a behavior that could be available in the engine. It's prone to many errors, and the contract size is pretty limited and duplicating a readonly-version of the methods would frequently overflow the maximum contract code size.

I don't know if extending `icx_call` or adding a new API endpoint would be the best design. I certainly can't help implementing it in the goloop engine, but I can help with supporting it in the official SDKs if needed.

**Comment by ICONationDevTeam** [comment]
Hey 👋  Any update on this issue ? Thanks !

**Comment by sink772** [comment]
Hi @ICONationDevTeam, We can't afford to spend time on this issue right now.
This kind of new API cannot be easily added to the engine code, since it increases code management cost once it is added.
And I think you may need to gather other ICON developers' opinion.  Currently, only you are requesting this API.
