### ISSUE TITLE
Expose 'LimitOfBatch` 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/goloop#73]
When indexing the chain, we used to for 1.0 batch our requests which allowed much faster syncing than if we sent synchronous requests.  Is it ok to expose the `LimitOfBatch` parameter that we can set via an environment variable?  

https://github.com/icon-project/goloop/blob/bb981dae67f799165cfa2f546fabd1ac89169ad1/server/jsonrpc/jsonrpc.go#L21

We can submit PR to include this.

**Comment by mksong-icon** [comment]
The development team discusses adding options for LimitOfBatch.
Your PR can't be merged, because it's not consistent with our current configuration propagation system.

**Comment by pranav925** [comment]
Hey @mksong-icon, revised and submitted another PR here: https://github.com/icon-project/goloop/pull/76

**Comment by mksong-icon** [comment]
@pranav925 We are planning to add a new configuration for it, but it will take some time. If you have urgency, then you can fork and patch it as you want for a moment.

**Comment by mksong-icon** [comment]
It's resolved with the commit, https://github.com/icon-project/goloop/commit/21ac0c39fbf353c9aa58a1b4a3b5cb522730feb3
