### ISSUE TITLE
getting node version from 'admin/chain/0x1' endpoint

### ISSUE THREAD

**Issue by FidelVe** [icon-project/goloop#88]
Hello team.

Im working on a telegram bot to help me manage my node server, most of the data I get from my node is by the `/admin/chain/0x1` endpoint.

I would like to know if its possible to add the current node version in the server in that endpoint or if there is another place where I can get that data.

Thanks!.

**Comment by mksong-icon** [comment]
https://github.com/icon-project/goloop/blob/master/doc/goloop_admin_api.md#view-system

**Comment by FidelVe** [comment]
thanks!
