### ISSUE TITLE
Websocket inconsistencies

### ISSUE THREAD

**Issue by alexdesousa** [icon-project/goloop#90]
Hello again! I'm trying to make sense of ICON 2.0 websockets' notifications and I'm having a hard time figuring them out. So far I have a working prototype where I can connect to the websocket and start receiving the notifications:

- I'm testing with `wss://ctz.solidwallet.io/api/v3/icon_dex/event` (Mainnet).
- I followed the documentation found [here](https://www.icondev.io/icon-node/goloop/json-rpc/btp_extension#events)
- I'm trying to subscribe to the `Swap` event from Balanced DEx:
  + Address: `cxa0af3165c08318e988cb30993b3048335b94af6c`
  + Signature: `Swap(int,Address,Address,Address,Address,Address,int,int,int,int,int,int,int,int,int)`
  + Match any indexed fields: `[null, null]`
  + Match any data fields: ` [null, null, null, null, null, null, null, null, null, null, null, null, null]`
  
> **Note**: I usually request the latest block height and use that height as starting height in the payload.

So, after establishing a connection with the websocket, I send the following `text` frame to the websocket (formatted for readability):

```json
{
  "height": "0x2cb7f81",
  "event": "Swap(int,Address,Address,Address,Address,Address,int,int,int,int,int,int,int,int,int)",
  "addr": "cxa0af3165c08318e988cb30993b3048335b94af6c",
  "indexed": [null, null],
  "data": [null, null, null, null, null, null, null, null, null, null, null, null, null]
}
```

So, the first notification I got was this one:

```json
{
  "events": ["0x4"],
  "hash": "0xa82d7793a972bd46550503ff23039f05e04da8df90d69735dfd2f96ab982b84b",
  "height": "0x2cb7f88",
  "index": "0x1"
}
```

So, what I understand about the notification:

- `height` is the height of the block: [46890888](https://tracker.icon.foundation/block/46890888)
- `hash` is the hash of the block: It matches the one shown in the previous link.
- `index` is the index of the transaction in `confirmed_transaction_list` which triggered the event. If we start counting from `0`, then it would be the second transaction in the block, which is [0xdd22de95b534b0be5b174aada9bb103d0fbc2bb5e0f02b85381b681c6f53ff28](https://tracker.icon.foundation/transaction/0xdd22de95b534b0be5b174aada9bb103d0fbc2bb5e0f02b85381b681c6f53ff28)
- `events` is a list of logs indexes where we can find the event that matched our initial query. So, the event I'm interested in would be the 5th log entry, but the event does not match the one I'm expecting:
  ```json
  {
    "scoreAddress":"cxb0b6f777fba13d62961ad8ce11be7ef6c4b2bcc6",
    "indexed": [
      "BetPlaced(int,int,int)",
      "0x4563918244f40000",
      "0x58",
      "0x0"
    ],
    "data":[]
  }
  ```

So, the result doesn't seem consistent with my first request. Is the payload incorrect? Or did I stumble upon a bug?

[This](https://github.com/alexdesousa/icon/pull/2) is the PR I'm working on at the moment in my Elixir ICON 2.0 SDK if you're curious of what I'm trying to accomplish.

**Comment by ajaya-man** [comment]
The swap event you are looking for is in `height-1` block i.e. [46890887](https://tracker.icon.foundation/block/46890887). 
The transaction is in index 1 and the event log is in index [4 or 5th item](https://tracker.icon.foundation/transaction/0x8b790982a10c417759531dfd21c38557ea18f89322935035655c9e8941fa6b85#events). 
Note: The event logs should be counted from downwards in tracker.

**Comment by alexdesousa** [comment]
@ajaya-man Thank you very much! This answer has been very helpful! I'll recheck my code and I'll start pulling data again :) I'll close the issue once I'm certain I understood your answer. Again, thanks for the fast response! :rocket:

**Comment by ajaya-man** [comment]
Also, @alexdesousa indexed and data are optional parameters, so you can skip them.

**Comment by alexdesousa** [comment]
@ajaya-man One follow up question: how should I interpret the payload for `/api/v3/icon_dex/block`? e.g. if I use the following to subscribe to the notifications:

```json
{
  "height": "0x2cb7f81",
  "eventFilters": [
    "event": "Swap(int,Address,Address,Address,Address,Address,int,int,int,int,int,int,int,int,int)",
    "addr": "cxa0af3165c08318e988cb30993b3048335b94af6c",
    "indexed": [null, null],
    "data": [null, null, null, null, null, null, null, null, null, null, null, null, null]
  ]
}
```

yet, the notifications seem to be incomplete:

```json
{
  "hash": "0xa82d7793a972bd46550503ff23039f05e04da8df90d69735dfd2f96ab982b84b",
  "height": "0x2cb7f88"
}
```

This is the same notification I get when I subscribe with this message:

```json
{
  "height": "0x2cb7f81"
}
```

I'm not sure what I'm doing wrong though :grimacing: Any help you can provide will be greatly appreciated :pray:

**Comment by ajaya-man** [comment]
On `/api/v3/icon_dex/block` you should be sending in the following way:
```json
{
  "height": "46806104",
  "eventFilters": [
    {
      "event": "Transfer(Address,Address,int,bytes)"
    }
  ]
}
```

The response would come for every new block as well in case the event is present there will be additional logs. 
Sample:
```json
{
  "hash": "0x834aaede99d90be33223328b36c51e22feab7db54cd153f35ed1b1392e938bc3",
  "height": "0x2ca3605"
}

{
  "hash": "0x6aa2ef0c459b4db894444bbbede0c818ebcf3c73ba5d0c872ac7d7bcfa54453f",
  "height": "0x2ca3604",
  "indexes": [
    [
      "0x1"
    ]
  ],
  "events": [
    [
      [
        "0x0",
        "0x1",
        "0x2",
        "0x3",
        "0x5",
        "0x6",
        "0x7",
        "0x9"
      ]
    ]
  ]
}

{
  "hash": "0x10f2aec7bd7fb0431216a69671d2fdd73ef04b254031fc7d293782426599117b",
  "height": "0x2ca3603"
}
```

**Comment by mksong-icon** [comment]
With `/api/v3/icon_dex/block`, it always sends block update notifications even if there are no events. It's for tracking the last block height for further request after disconnection.

**Comment by alexdesousa** [comment]
@ajaya-man Thank you very much for your answers! They have been very helpful for me to finish my websocket code! I consider this issue is solved :slightly_smiling_face: :rocket:
