### ISSUE TITLE
getBonderList RPC call return wrong value 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/goloop#91]
When calling getBonderList on the foundation address wallet address (hx0b047c751658f7ce1b2595da34d57a0e7dad357d), it returns two values for the bond `["hxb86afed8db896012664b0fa6c874fe0e3001edaf", "hx7062a97bed64624846f3134fdab3fb856dce7075"]` where one address [hx7062a97bed64624846f3134fdab3fb856dce7075](https://tracker.icon.foundation/address/hx7062a97bed64624846f3134fdab3fb856dce7075) does not have any Txs to the governance address so it could not have bonded.  What is interesting is that it did [Tx the bond amount](https://tracker.icon.foundation/transaction/0xa6605c66472f45d75a035120bb3214f626a0d5b1315c670777048d70b4478ffd) to the actual bonding address but never submitted a bond directly. 

RPC Call 
```
{
        "jsonrpc": "2.0",
        "id": 1234,
        "method": "icx_call",
        "params": {
            "to": "cx0000000000000000000000000000000000000000",
            "dataType": "call",
            "data": {
                "method": "getBonderList",
                "params": {
                    "address": "hx0b047c751658f7ce1b2595da34d57a0e7dad357d",
                }
            }
        }
    }
```

**Comment by mksong-icon** [comment]
`getBonderList` returns a list of accounts which can call `setBond` with voting power for the PRep.
`getBond` returns the current status of bonds.

**Comment by mksong-icon** [comment]
```
# goloop rpc call --to cx0000000000000000000000000000000000000000 --method getBonderList --param address=hx0b047c751658f7ce1b2595da34d57a0e7dad357d
{
  "bonderList": [
    "hxb86afed8db896012664b0fa6c874fe0e3001edaf",
    "hx7062a97bed64624846f3134fdab3fb856dce7075"
  ]
}
```
For PRep `hx0b047c751658f7ce1b2595da34d57a0e7dad357d`, two accounts ( `hxb86afed8db896012664b0fa6c874fe0e3001edaf` and `hx7062a97bed64624846f3134fdab3fb856dce7075` ) are allowed to set bond.

**Comment by mksong-icon** [comment]
To set bond, target address is not governance, but chain score, `cx0000000000000000000000000000000000000000`.
Here is [the tx](https://tracker.icon.foundation/transaction/0xae0a97b3f9f0c3b3cc4a154b1cc8abe7424293defdcb89f3ef60bb772a5d2ed5) for bonds.

**Comment by robcxyz** [comment]
@mksong-icon - Thank you for clearing this up.  Makes sense thank you. Closing.
