### ISSUE TITLE
getPReps RPC returning wrong data 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/goloop#92]
Running getPReps (RPC below) returns what I believe is old data from ICON 1.0 as the `p2pEndpoint` is not right for a lot of nodes. For instance for `ICON Asset Management`, the right IP is `54.68.57.186` which calling the below RPC returns                 `"p2pEndpoint": "44.235.212.252:7100"`. 

```json
{
  "jsonrpc": "2.0",
  "id": 1234,
  "method": "icx_call",
  "params": {
    "to": "cx0000000000000000000000000000000000000000",
    "dataType": "call",
    "data": {
      "method": "getPReps",
      "params": {
        "startRanking": "0x1",
        "endRanking": "0xaaa"
      }
    }
  }
}
```

**Comment by mksong-icon** [comment]
Actually, after ICON 2.x, it's a deprecated field. So please don't depend on it.

**Comment by robcxyz** [comment]
@mksong-icon - Is there a replacement for this RPC call?  Also is it just that field (p2pEndpoint) or is it the whole call?

**Comment by sink772** [comment]
@robcxyz You can use `getPReps` as before except the `p2pEndpoint` field.  All other information are valid.
