### ISSUE TITLE
Getting odd status code some calls 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/goloop#99]
We are getting some odd responses that we have never seen before on **sejong**. 

```
StatusCode=400,
Request={
"jsonrpc": "2.0",
"id": 1234,
"method": "icx_call",
"params": {
    "to": "cxf5f3c028cedc26ec4740edecb926e6eee52b697f",
    "dataType": "call",
    "data": {
        "method": "decimals",
        "params": {}
    }
}
},
Response={"jsonrpc":"2.0","error":{"code":-30001,
"message":"SystemError(-30001): E0001:ProxyIsClosed"},"id":1234}
```

[Contract exists](https://sejong.tracker.solidwallet.io/contract/cxf5f3c028cedc26ec4740edecb926e6eee52b697f). Call works fine against solidwallet / geometry endpoints but failing against a bare metal node that has batch set to 1000.

**Comment by sink772** [comment]
> failing against a bare metal node that has batch set to 1000.
What do you mean by above sentence?  You are running a goloop node that has configured to accept 1000 batch RPC requests?

**Comment by robcxyz** [comment]
@sink772 - Correct, we set this by exec-ing into the container. 

```shell
goloop system config rpcIncludeDebug true
goloop system config rpcBatchLimit 1000
```

We have been doing some experimenting around what to set the batch from (10, to 100, to 1000) as we are trying to be able to send massive volumes of RPC calls to a node for indexing.  We just built this tool - https://github.com/sudoblockio/icon-extractor - which seems to be overloading goloop with requests.  

I started another issue #100 around performance as this issue is really about the "ProxyIsClosed" error coming from the OnClose method.  They could be related though if the node is crashing a lot and this is just the error we get at the end.  When we have been doing high load tests, we haven't been typically seeing this error though and don't want assume they are related.

**Comment by sink772** [comment]
Can you provide us the goloop node logs when the "ProxyIsClosed" error occurs?  We need to get some hints from the logs.

**Comment by robcxyz** [comment]
Hi @sink772 - I have not seen these since I reduced batch to 10.  I am going to keep note of this and associated issues and when bandwidth is more available, try to look more into this and issues around #100. Will keep in touch with you all over private channels on this.
